language: node_js

node_js:
    - "5"
    - "6"
    - "7"

sudo: false

script:
    - npm run lint
    - npm run test
    - npm run coverage

after_success:
    - npm run coveralls
    - npm run codeclimate

notifications:
    email:
        tom@x-c-o-d-e.com
